package com.myspace.streaming_alerts_system;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Event")
public class Event implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Event ID")
	private int event_id;
	@org.kie.api.definition.type.Label(value = "Event Name")
	private java.lang.String event_name;

	@org.kie.api.definition.type.Label(value = "Event Date")
	private java.util.Date event_date;

	@org.kie.api.definition.type.Label(value = "Location")
	private java.lang.String location;

	@org.kie.api.definition.type.Label(value = "Parameter Name")
	private java.lang.String parameter_name;

	@org.kie.api.definition.type.Label(value = "Parameter Value")
	private float parameter_value;
	public Event() {
	}

	public int getEvent_id() {
		return this.event_id;
	}

	public void setEvent_id(int event_id) {
		this.event_id = event_id;
	}

	public java.lang.String getEvent_name() {
		return this.event_name;
	}

	public void setEvent_name(java.lang.String event_name) {
		this.event_name = event_name;
	}

	public java.util.Date getEvent_date() {
		return this.event_date;
	}

	public void setEvent_date(java.util.Date event_date) {
		this.event_date = event_date;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getParameter_name() {
		return this.parameter_name;
	}

	public void setParameter_name(java.lang.String parameter_name) {
		this.parameter_name = parameter_name;
	}

	public float getParameter_value() {
		return this.parameter_value;
	}

	public void setParameter_value(float parameter_value) {
		this.parameter_value = parameter_value;
	}

	public Event(int event_id, java.lang.String event_name,
			java.util.Date event_date, java.lang.String location,
			java.lang.String parameter_name, float parameter_value) {
		this.event_id = event_id;
		this.event_name = event_name;
		this.event_date = event_date;
		this.location = location;
		this.parameter_name = parameter_name;
		this.parameter_value = parameter_value;
	}

}