package com.myspace.streaming_alerts_system;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Subscription")
public class Subscription implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Subscription Id")
	private int subscription_id;
	@org.kie.api.definition.type.Label(value = "Event ID")
	private int event_id;
	@org.kie.api.definition.type.Label(value = "Alert Name")
	private java.lang.String alert_name;
	@org.kie.api.definition.type.Label(value = "Alert Location")
	private java.lang.String alert_location;
	@org.kie.api.definition.type.Label(value = "Start Date")
	private java.util.Date start_date;
	@org.kie.api.definition.type.Label(value = "End Date")
	private java.util.Date end_date;
	@org.kie.api.definition.type.Label(value = "Threshold")
	private float threshold;

	public Subscription() {
	}

	public int getSubscription_id() {
		return this.subscription_id;
	}

	public void setSubscription_id(int subscription_id) {
		this.subscription_id = subscription_id;
	}

	public int getEvent_id() {
		return this.event_id;
	}

	public void setEvent_id(int event_id) {
		this.event_id = event_id;
	}

	public java.lang.String getAlert_name() {
		return this.alert_name;
	}

	public void setAlert_name(java.lang.String alert_name) {
		this.alert_name = alert_name;
	}

	public java.lang.String getAlert_location() {
		return this.alert_location;
	}

	public void setAlert_location(java.lang.String alert_location) {
		this.alert_location = alert_location;
	}

	public java.util.Date getStart_date() {
		return this.start_date;
	}

	public void setStart_date(java.util.Date start_date) {
		this.start_date = start_date;
	}

	public java.util.Date getEnd_date() {
		return this.end_date;
	}

	public void setEnd_date(java.util.Date end_date) {
		this.end_date = end_date;
	}

	public float getThreshold() {
		return this.threshold;
	}

	public void setThreshold(float threshold) {
		this.threshold = threshold;
	}

	public Subscription(int subscription_id, int event_id,
			java.lang.String alert_name, java.lang.String alert_location,
			java.util.Date start_date, java.util.Date end_date, float threshold) {
		this.subscription_id = subscription_id;
		this.event_id = event_id;
		this.alert_name = alert_name;
		this.alert_location = alert_location;
		this.start_date = start_date;
		this.end_date = end_date;
		this.threshold = threshold;
	}

}